[package]
name = "revshell"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
igd-next = { version = "0.16.2", features = ["aio_tokio", "tokio"] }
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
